### PR TITLE
fix: implement position for mobile screen

### LINKED ISSUE #226: [Frontend] Create position mini-app
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Ask me in telegram(djeck_vorobey1) to get access to figma, send me your email in message
3. Add create position(form) for mobile version 
4. Make sure all endpoints work as before

### PR DESCRIPTION
**Pull request by wheval**
fixes #226

### CODE REVIEW

File: frontend/src/components/BalanceCards.jsx [hunk 1]
```diff
@@ -15,35 +15,61 @@ const BalanceCards = ({ walletId }) => {
...
+  
+  const handleScroll = () => {
+    if (scrollRef.current) {
+      const { scrollLeft, scrollWidth, clientWidth } = scrollRef.current;
+      const scrollPercentage = scrollLeft / (scrollWidth - clientWidth);
+      const index = Math.round(scrollPercentage);
+      setActiveIndex(index);
+    }
+  };
+
```
Comment (whateverfw) [inline frontend/src/components/BalanceCards.jsx:29]: extract whole scrolling functionality to a custom hook

File: frontend/src/pages/forms/form.css [hunk 2]
```diff
@@ -322,45 +347,130 @@ input[type='number'].error {
...
+  .balance-item:last-child {
+    margin-right: 20px;
+  }
+  .balance-item .balance-title {
+    font-size: 1rem;
+    display: flex;
+    align-items: center;
+  }
+  .balance-item > label {
+    font-size: 2rem !important;
```
Comment (whateverfw) [inline frontend/src/pages/forms/form.css:409]: avoid using important

File: frontend/src/pages/forms/form.css [hunk 3]
```diff
@@ -322,45 +347,130 @@ input[type='number'].error {
...
-  margin-right: 5px;
   height: 25px;
   width: 24px;
 }
 
 /* Responsiveness */
 @media (max-width: 768px) {
+  .form-container {
+    margin-top: 3rem !important;
+    padding: 0 !important;
```
Comment (whateverfw) [inline frontend/src/pages/forms/form.css:358]: avoid important

File: frontend/src/pages/forms/form.css
Comment (whateverfw) [inline frontend/src/pages/forms/form.css:1]: remove commented parts, also use css variables for colors

File: frontend/src/components/BalanceCards.jsx [hunk 4]
```diff
@@ -15,35 +15,61 @@ const BalanceCards = ({ walletId }) => {
...
             <label htmlFor={balance.title}>{balance.balance}</label>
           </div>
         )
       )}
     </div>
+      <div className="pagination">
+        <div className={`dot ${activeIndex === 0 ? "active" : ""}`}></div>
+        <div className={`dot ${activeIndex === 1 ? "active" : ""}`}></div>
+      </div>
+      </div>
```
Comment (whateverfw) [inline frontend/src/components/BalanceCards.jsx:72]: create a separate component for this, number of dots should be dynamic, though, based on the number of balances, because in the future there can be more than 4 balances, so it should be calculated, like dot per each 2 balances.

Also, each dot should be clickable and scroll horizontally to the left or right

**Review by whateverfw — CHANGES_REQUESTED** [review]
telegram-cloud-photo-size-2-5334852296988812740-y

balance cards is broken on both tablet/mobile (has some big margin from left)

also fix gaps between selectable tokens (broken on tablet), it should probably don't have such big gaps, rather be centered 

also, stars should not be visible on mobile according to figma

File: frontend/src/components/BalanceCards.jsx (hunk 4 above)
Comment (wheval) [reply frontend/src/components/BalanceCards.jsx:72]: okay, on it

File: frontend/src/pages/forms/Form.jsx [hunk 5]
```diff
@@ -5,21 +5,13 @@ import MultiplierSelector from 'components/MultiplierSelector';
 import { connectWallet } from 'services/wallet';
 import { handleTransaction } from 'services/transaction';
 import Spinner from 'components/spinner/Spinner';
-import StarMaker from 'components/StarMaker';
-import CardGradients from 'components/CardGradients';
```
Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:9]: you shouldn't remove it, as it still should be preset on a desktop screens, you need to adjust it on mobile, to correspond to figma and make sure it still works the same for desktop

**Review by whateverfw — CHANGES_REQUESTED** [review]

**Comment by wheval** [comment]
@whateverfw

**Comment by whateverfw** [comment]
@wheval please take a look into screen w/ 390px width, "Select token" section doesn't fit the screen, please take a look into figma and make it accordingly, at least I can say that font size should be smaller on mobile devices, verify other things to match design as well.

**Comment by whateverfw** [comment]
@wheval Also page background still don't match figma

**Comment by wheval** [comment]
> @wheval please take a look into screen w/ 390px width, "Select token" section doesn't fit the screen, please take a look into figma and make it accordingly, at least I can say that font size should be smaller on mobile devices, verify other things to match design as well.

okay

**Comment by whateverfw** [comment]
@wheval Make sure to resolve merge conflicts with main

**Comment by djeck1432** [comment]
@wheval fix merge conflict and fix all comments which are left as soon as possible, otherwise you will be unassigned !

**Comment by wheval** [comment]
on it sir!

**Comment by whateverfw** [comment]
@wheval any updates?

**Comment by wheval** [comment]
@whateverfw almost done sir

**Comment by wheval** [comment]
I am working on the slider already ser

**Comment by djeck1432** [comment]
@wheval Any updates?

**Comment by djeck1432** [comment]
@wheval Any updates? 18 hours ago last commit,

File: frontend/src/components/TokenSelector.jsx
Comment (whateverfw) [inline frontend/src/components/TokenSelector.jsx:1]: Font of token label doesn't match figma, should, ER: 14px, AR: 16px

File: frontend/src/components/MultiplierSelector.jsx
Comment (whateverfw) [inline frontend/src/components/MultiplierSelector.jsx:1]: I can't select x1 multiplier at all

Comment (whateverfw) [inline frontend/src/components/MultiplierSelector.jsx:1]: There should be 0x-10x options, currently it is 1x-5x

Comment (whateverfw) [inline frontend/src/components/MultiplierSelector.jsx:1]: Slider should feel smoothly, currently when I try to drag a dot - it instantly selects me next multiple value (.e.g. if it was 2x and I try to drag to start dragging - it instantly jumps to 3x, not allowing me to drag it into desired direction)

File: frontend/src/components/BalanceCards.jsx
Comment (whateverfw) [inline frontend/src/components/BalanceCards.jsx:1]: Balance cards sizes don't match figma.

File: frontend/src/pages/forms/Form.jsx
Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:1]: Page background slightly don't match Figma, take a look into the top part

Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:1]: Some fonts sizes/weights don't match figma (e.g. title one, or the once above inputs/selects)

Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:1]: Vertical margin don't match Figma, please take a look and make it just like in Figma

**Review by whateverfw — CHANGES_REQUESTED** [review]
1)

File: frontend/src/components/MultiplierSelector.jsx
Comment (wheval) [reply frontend/src/components/MultiplierSelector.jsx:1]: I thought it should depend on the selected Token, I would fix this asap.

Comment (whateverfw) [reply frontend/src/components/MultiplierSelector.jsx:1]: @wheval Yeah, sorry, it should be dynamic, depending on what is selected and what was returned from a backend

Comment (whateverfw) [reply frontend/src/components/MultiplierSelector.jsx:1]: There is another issue though

1) You selected a token with max 5x multiplier, and 3x or 4x or 5x is elected, whatever
2) You switch to a token with max 2x multiplier and dot disappear (because it was selected for another token with higher value)

I suggest to probably check and reselet max possible value when token is switched, so multiplier/dot is always correctly selected and visible, depending on  a token

Comment (whateverfw) [reply frontend/src/components/MultiplierSelector.jsx:1]: @wheval and let's keep min multiplier as x1 (just like you did)

Comment (wheval) [reply frontend/src/components/MultiplierSelector.jsx:1]: i'm waiting for your confirmation @whateverfw

Comment (whateverfw) [reply frontend/src/components/MultiplierSelector.jsx:1]: @wheval I've already provided all the answers above

Comment (wheval) [reply frontend/src/components/MultiplierSelector.jsx:1]: @djeck1432 I have fixed it

**Review by whateverfw — CHANGES_REQUESTED** [review]
@wheval Ok, most of the bug are fixed, thanks!

The last issue I see so far is related to what've partially fixed.
Preconditions:
* You've selected a token with a max multiplier of 5x
* Switched to a token with a max multiplier of 2x, now visually dot also switched to correspond to 2, but `selectedMultiplier` state is still old and equal to `5.0`, so if user click submit, it will send old value, instead of new one 


Also, when you do actions above and start dragging, you can clearly see in the console that value is 2.5 for some reason and not 2? Do you know the reason for that? 
Also sometimes it is like that, so basically x2 label is highlighted, but the dot somewhere in-between
image

**Review by whateverfw — CHANGES_REQUESTED** [review]
upd:

multiplier step should be 0.1 (make it at least functionally like that, for now don't need to represent it visually, so visually it will still be step 1)

**Also, please fix merge conflicts with main and make sure everything is functioning well**

**Comment by whateverfw** [comment]
@wheval fix failed CI

File: frontend/src/pages/forms/Form.jsx [hunk 6]
```diff
@@ -5,8 +5,11 @@ import MultiplierSelector from 'components/MultiplierSelector';
 import { connectWallet } from 'services/wallet';
 import { handleTransaction } from 'services/transaction';
 import Spinner from 'components/spinner/Spinner';
+<<<<<<< HEAD
+=======
 // import StarMaker from 'components/StarMaker';
```
Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:10]: please resolve conflicts here and everywhere, and test everything before your next commit

**Review by whateverfw — CHANGES_REQUESTED** [review]

File: frontend/src/pages/forms/Form.jsx (hunk 6 above)
Comment (wheval) [reply frontend/src/pages/forms/Form.jsx:10]: I just realized that another contributor worked on the Form page for the desktop screen.
So that's what is causing the conflict because I worked on both mobile and desktop screen.
Should I use conditionals to render the mobile version in another component or implement responsiveness again for what the previous contributor worked on?

Comment (whateverfw) [reply frontend/src/pages/forms/Form.jsx:10]: if you worked on both mobile and desktop versions, just go through everything making sure it is working well, it is ok to keep your changes and override previous ones 

@wheval

Comment (wheval) [reply frontend/src/pages/forms/Form.jsx:10]: @whateverfw

**Comment by whateverfw** [comment]
@wheval there is still some issue with a build, please check CI

**Comment by wheval** [comment]
> @wheval there is still some issue with a build, please check CI

I think I fixed it now.

**Review by djeck1432 — APPROVED** [review]
Looks good to me, hope next time you will do your task faster
