### PR TITLE
feat/fix to issue #242

### LINKED ISSUE #242: [FRONTEND] New position window mini-app
🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋
0. Please, join the telegram group to keep in touch https://t.me/+m0IGRiBvLtsyMzIy 
1. Read guideline [here](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5)
2. Add new window for pop-up for `mobile device` if user click on `submit form` and user has already opened position
3. Redirect user to dashboard to close position
4. Ask me in telegram(djeck_vorobey1) to get access to figma, send me your email in message

### PR DESCRIPTION
**Pull request by ekumamatthew**
Fix #242

### CODE REVIEW

**Review by djeck1432 — CHANGES_REQUESTED** [review]
Please, fix github workflow issue
https://github.com/djeck1432/spotnet/actions/runs/11984813605/job/33416020314?pr=248

File: frontend/src/pages/forms/Form.jsx [hunk 1]
```diff
@@ -30,27 +29,17 @@ const Form = ({ walletId, setWalletId }) => {
...
-    queryKey: ['hasOpenPosition', walletId],
-    queryFn: async () => {
-      if (!walletId) return { has_opened_position: false };
-      const { data } = await axios.get('/api/has-user-opened-position', {
-        params: { wallet_id: walletId },
-      });
-      return data;
-    },
-    enabled: !!walletId,
-  });
```
Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:46]: why this was removed?

File: frontend/src/pages/forms/Form.jsx [hunk 2]
```diff
@@ -30,27 +29,17 @@ const Form = ({ walletId, setWalletId }) => {
...
+  const navigate = useNavigate();
+  useLockBodyScroll(successful);
 
   const connectWalletHandler = async () => {
     try {
       setError(null);
       const address = await connectWallet();
       if (address) {
-        setWalletId(address);
+        setWalletId(address); // Correctly set the walletId using the passed setWalletId function
```
Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:42]: remove comment

File: frontend/src/pages/forms/Form.jsx [hunk 3]
```diff
@@ -63,52 +52,48 @@ const Form = ({ walletId, setWalletId }) => {
     }
     return null;
   };
+  const checkOpenPosition = () => {
+    // write api check for position
+    return true;
+  };
```
Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:58]: finish this, seems like you could use pervious API call and based on that either proceed or show position modal?

File: frontend/src/components/modals/modal.css
Comment (whateverfw) [inline frontend/src/components/modals/modal.css:1]: use css variables for all colors, it should be put into global.css

File: frontend/src/pages/forms/Form.jsx [hunk 4]
```diff
@@ -1,20 +1,19 @@
-import React, { useState } from 'react';
-import TokenSelector from 'components/TokenSelector';
+import { ReactComponent as AlertHexagon } from 'assets/icons/alert_hexagon.svg';
 import BalanceCards from 'components/BalanceCards';
+import CardGradients from 'components/CardGradients';
+import CongratulationsModal from 'components/congratulationsModal/CongratulationsModal';
+import PositionModal from 'components/modals/Modal';
```
Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:5]: you are importing components/modals/Modal, but your file is named `modal` so it should be components/modals/modal 

Currently it will fail to build

**Review by whateverfw — CHANGES_REQUESTED** [review]

File: frontend/src/pages/forms/Form.jsx (hunk 4 above)
Comment (whateverfw) [reply frontend/src/pages/forms/Form.jsx:5]: And in general, you should give more meaningful name to a file, ClosePositionModal (e.g.)

**Comment by whateverfw** [comment]
@ekumamatthew any updates?

**Comment by ekumamatthew** [comment]
Updating my PR shortly

File: frontend/src/components/modals/ClosePositionModal.css
Comment (whateverfw) [inline frontend/src/components/modals/ClosePositionModal.css:1]: styles don't match figma, please take a look how other models implemented already (e.g. notification one on dashboard)

File: frontend/src/pages/forms/Form.jsx [hunk 5]
```diff
@@ -30,8 +31,7 @@ const Form = ({ walletId, setWalletId }) => {
   const [loading, setLoading] = useState(false);
   const [alertMessage, setAlertMessage] = useState('');
   const [successful, setSuccessful] = useState(false);
-  useLockBodyScroll(successful);
-  const [showPopup, setShowPopup] = useState(false);
+  const [positionModal, setPositionModal] = useState(false);
 
   const { data: positionData, refetch: refetchPosition } = useQuery({
```
Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:36]: this doesn't work, please test it before your next commit, axiosIntance should be used instead of axios, currently it doesn't do request to a backend..

File: frontend/src/pages/forms/Form.jsx [hunk 6]
```diff
@@ -30,8 +31,7 @@ const Form = ({ walletId, setWalletId }) => {
   const [loading, setLoading] = useState(false);
   const [alertMessage, setAlertMessage] = useState('');
   const [successful, setSuccessful] = useState(false);
-  useLockBodyScroll(successful);
-  const [showPopup, setShowPopup] = useState(false);
+  const [positionModal, setPositionModal] = useState(false);
```
Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:34]: this should be renamed to `isPositionModalOpened

**Review by whateverfw — CHANGES_REQUESTED** [review]

**Comment by djeck1432** [comment]
@ekumamatthew Any updates?

File: frontend/src/pages/forms/Form.jsx (hunk 5 above)
Comment (whateverfw) [reply frontend/src/pages/forms/Form.jsx]: resolved

File: frontend/src/pages/forms/Form.jsx (hunk 6 above)
Comment (whateverfw) [reply frontend/src/pages/forms/Form.jsx]: resolved

File: frontend/src/components/modals/ClosePositionModal.css
Comment (whateverfw) [reply frontend/src/components/modals/ClosePositionModal.css:1]: @ekumamatthew this is still unresolved after latest changes), also - modal should be centered on the screen

**Review by whateverfw — CHANGES_REQUESTED** [review]
@ekumamatthew seems like some of your changes were overwritten after your latest merges, (Form.jsx), please take a look and fix, thanks

**Comment by ekumamatthew** [comment]
I made the position function a hook. so that it can be re-useable anytime

**Review by whateverfw — CHANGES_REQUESTED** [review]
So, functionally-wise everything is fine.

But as I already pointed there are issues with modal's styling.

ER (Figma):
image

AR (Your implementation):
image

You should do it exactly the same as in Figma. As I already suggested you already have the same modal on dashboard for notifications, just use the same styles as there...

**Comment by ekumamatthew** [comment]
I used the position modal component present in the dashboard. I only made the buttons mobile responsive cause on mobile the border radious almost take an oval shape

**Comment by whateverfw** [comment]
@ekumamatthew

Your modal:
image

image

1) Modal Background color is different 
2) Inside padding is different
3) Button location is wrong
4) Button shape is wrong
5) Button size is wrong
6) Cancel Button color
7) Font sizes are different
9) Text colors
8) Margins are different
10) Every part is different

I can clearly see the difference and I've already requested the same changes 3rd or 4th time, nothing changes each time

**Comment by djeck1432** [comment]
@ekumamatthew We are seeing that you can't manage this task, that is why you have last chance to read carefully comments and resolve them. Please, pay attention to css style as in figma

**Comment by djeck1432** [comment]
@ekumamatthew Any updates?

**Comment by ekumamatthew** [comment]
Worked on the design..  Will be updating my pr shorlty

**Comment by djeck1432** [comment]
@ekumamatthew any updates, you are blocking other contributors to get their new issue, please, finish it as soon as possible, you have been working on it 3 days

**Comment by djeck1432** [comment]
@ekumamatthew please sync with main branch

**Comment by djeck1432** [comment]
@ekumamatthew Please, fix all pipeline issues

**Comment by ekumamatthew** [comment]
i'm having this issue with background image upload. tried both svg and png... that's whats breaking the front end pipeline:

large screen
modal
tabscreen


this is  for large, tab and small screen.

Also when I sync my update the form page component design is doubled but there is a comment that no changes should be mad. i didn't fix that cause I feel there's a reason for that because of the comment

**Comment by whateverfw** [comment]
@ekumamatthew put your background file to public folder and use it in css like that `url('/public/background.png')`, as you can see in other places (`form.css, dashboard.css, withdraw.css`). Also I still see font color mismatches with figma.

**Review by whateverfw — CHANGES_REQUESTED** [review]
@ekumamatthew ⏫

**Comment by ekumamatthew** [comment]
Font colour... okay. I'll look at the figma again

**Comment by ekumamatthew** [comment]
I had a look at the figma text color its same here

**Comment by whateverfw** [comment]
@ekumamatthew `Form.jsx:141 Uncaught ReferenceError: StyledPopup is not defined` when I try to access form page.....

**Comment by whateverfw** [comment]
@ekumamatthew this page is completely broken now, there are everything duplicated, probably it was wrong resolvment of merge conflict

**Comment by whateverfw** [comment]
@ekumamatthew don't use `StyledPopup` in this componen anymore, use your ClosePositionModal, but fix mobile, 
image
that's how it currently looks..

**Comment by whateverfw** [comment]
@ekumamatthew Also, now I realise that you don't need background image for popup at all, in figma it is just a demonstration that on the background should be actual page, not some image, so remove ` background-image: url('/public/positionBg.svg');`

**Comment by whateverfw** [comment]
@ekumamatthew also, please resolve merge conflicts with main and make sure everything works, (last time I've checked font color were ok), just need to merge it properly and correctly use your modal component and not `styledpopup`

**Comment by djeck1432** [comment]
@ekumamatthew Please, fix test cases

**Comment by ekumamatthew** [comment]
ive sync with origin.  i'm getting along with the UI and the project better ... also the ui is not so mobile fit. I can fix this if I'm pointed to the UI.. so u can
 make it an issue i'd fix

**Comment by whateverfw** [comment]
@ekumamatthew now the whole Form  page is completely broken...
image

can you please revert  css changes that do not relate to close position popup?

**Comment by djeck1432** [comment]
@ekumamatthew please, text me in dm, I'm going to unassign you, sorry, this critical task and we need to finish it right away

File: frontend/src/pages/forms/Form.jsx [hunk 7]
```diff
@@ -74,56 +75,64 @@ const Form = ({ walletId, setWalletId }) => {
...
-    setShowPopup(false);
-  };
-
   const handleClosePosition = () => {
+    setIsPositionModalOpened(false);
     window.location.href = '/dashboard';
   };
-
   return (
-    <div className="form-content-wrapper">
```
Comment (whateverfw) [inline frontend/src/pages/forms/Form.jsx:87]: removing this container cause broken ui on the page..

**Review by whateverfw — CHANGES_REQUESTED** [review]

**Comment by whateverfw** [comment]
@ekumamatthew also seems like background on the main page is broken now on this branch for some reason.

**Comment by whateverfw** [comment]
@ekumamatthew please fix failed CI build

**Comment by whateverfw** [comment]
@ekumamatthew you should build your app before you commit and make sure it works.

**Review by djeck1432 — APPROVED** [review]
Sorry, we need to close this task and fix what was left, you will get partially reward
