### PR TITLE
feat(admin): add admin positions page, fix React version mismatch, an…

### LINKED ISSUE #844: [Margin frontend] Add order list to display all opened position
> 🚨 **Attention: Please read the guidelines before applying; otherwise, you will be ignored.** 🚫📋

## Guidelines
1. **Telegram**: Please join our [Telegram group](https://t.me/+m0IGRiBvLtsyMzIy) to keep in touch.
2. **Read the guideline**: Please read [this guideline](https://gist.github.com/djeck1432/f722f5fe518c80b248ff609627da25e5) thoroughly before starting.

## Task description
1. We need to have admin to analyze and see all opened position in real time.
2. Set up backend part using this [README.md](https://github.com/djeck1432/spotnet/blob/main/margin/README.md)
3. Don't forget to run [seed_data](https://github.com/djeck1432/spotnet/blob/main/margin/README.md#5-seed-data-generator) to populate db 
4. After that in `margin_frontend` [folder](https://github.com/djeck1432/spotnet/tree/main/margin/margin_frontend) add new page with next routing: `admin/positions`
5. Please use this `http://localhost:5173/app/sales/order-list` example of table data with next fields:
list of:
```
    id: UUID
    user_id: UUID
    borrowed_amount: Decimal
    multiplier: int
    transaction_id: str
    status: str
    liquidated_at: datetime | None
```
Use backend endpoint `http://0.0.0.0:8000/api/margin/all?limit=25&offset=0`

6. Template is located  [here](https://github.com/djeck1432/spotnet/tree/main/margin/margin_frontend/admin_template)
7. To run demo and see how it looks go to `demo` [folder](https://github.com/djeck1432/spotnet/tree/main/margin/margin_frontend/admin_template/demo) 
8. All Fronted code should be [here](https://github.com/djeck1432/spotnet/tree/main/margin/margin_frontend/src) NOT in `admin_template`

### PR DESCRIPTION
**Pull request by Dannynsikak**
…d updated Docker/dev setup

this PR closes #844 with the following changes 
- Implemented the /admin/positions page in the margin frontend to display all open margin positions in real time, using Ant Design Table and the provided admin template for UI consistency.
- Fixed a critical React/ReactDOM version mismatch in package.json to resolve frontend rendering errors.
- Updated Docker Compose and .env files to ensure the backend, frontend, and database run together smoothly, and seeded the database with test data.
- Verified backend API returns correct data and frontend fetches and displays it as expected.
- Addressed and documented common dev warnings (e.g., mixed content in Codespaces, @tanstack/router-devtools deprecation).

### CODE REVIEW

File: margin/margin_frontend/src/routes/admin/positions.tsx [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+    axios.get('http://0.0.0.0:8000/api/margin/all?limit=25&offset=0')
+      .then(res => {
+        setData(res.data.results || res.data || []);
+        setLoading(false);
+      })
+      .catch(err => {
+        setError('Failed to fetch positions');
+        setLoading(false);
+      });
+  }, []);
```
Comment (vadim-ghostman) [inline margin/margin_frontend/src/routes/admin/positions.tsx:32]: review backend endpoint response and adjust data fetching

File: devops/docker-compose.margin.fullstack.yml
Comment (vadim-ghostman) [inline devops/docker-compose.margin.fullstack.yml:1]: is this really needed?

for now, `docker-compose.margin.back.yml` doing that's all

**Review by vadim-ghostman — CHANGES_REQUESTED** [review]
design can be better (like [here](https://elstar.themenate.net/app/sales/order-list))

for table, you can take it from `admin_template` folder

how it looks now (ID's can be shortened and be copied on click):
image

example look (for now, it can be without pagination, but efforts will be welcomed):
image

also, fix data fetching

File: devops/docker-compose.margin.fullstack.yml
Comment (Dannynsikak) [reply devops/docker-compose.margin.fullstack.yml:1]: okay, i will take it out now

File: margin/margin_frontend/.env.dev
[the remark this answers is not in the document]
Comment (Dannynsikak) [reply margin/margin_frontend/.env.dev:1]: removed

**Comment by Dannynsikak** [comment]
> hi, design can be better (like [here](https://elstar.themenate.net/app/sales/order-list))
> 
> for table, you can take it from `admin_template` folder
> 
> how it looks now (ID's can be shortened and be copied on click): image
> 
> example look (for now, it can be without pagination, but efforts will be welcomed): image
> 
> p.s. dark theme is preffered

done sir

File: margin/margin_frontend/src/ui/components/Table.tsx
Comment (vadim-ghostman) [inline margin/margin_frontend/src/ui/components/Table.tsx:1]: where is Table component?

File: devops/docker-compose.margin.fullstack.yml
Comment (vadim-ghostman) [inline devops/docker-compose.margin.fullstack.yml:1]: don't leave empty file, remove it

File: margin/margin_frontend/Dockerfile [hunk 2]
```diff
@@ -4,7 +4,8 @@ ENV PATH "/app/node_modules/.bin:$PATH"
 
 WORKDIR /src
 
-COPY ./package.json ./package-lock.json .
+COPY ./package.json .
+COPY ./yarn.lock .
```
Comment (vadim-ghostman) [inline margin/margin_frontend/Dockerfile:8]: there can be used just one `COPY` command instead of two

**Review by vadim-ghostman — CHANGES_REQUESTED** [review]

**Review by vadim-ghostman — APPROVED** [review]
looks good to me
